display:
    new: ENC[AES256_GCM,data:diaJsw==,iv:cH/pCJrDdS4a1HA9nmwqT9af3VG514sKenGtiDQxusU=,tag:b0Em1KmQfZ3qnModejfh0Q==,type:bool]
    error: ENC[AES256_GCM,data:pcSWZA==,iv:Wc73llSMAQYqGCAewHO1aNO1o1w3pX7BWv5BkaIwVP8=,tag:73Sbnsskef/nlqjeUDUTAw==,type:bool]
    unchanged: ENC[AES256_GCM,data:rZSOkJE=,iv:teK5lp7umzHGXS3CshqOu/EtXtTlO7jgpVRlALSfK78=,tag:BVhxiQ9jyNfBnegonDITiQ==,type:bool]
    empty-diff: ENC[AES256_GCM,data:jWVXXQ==,iv:3j6+ihkcOFDg5Xk9CZBD2OxmX8yYiM5Hm3G1+NY1Xlk=,tag:Sv5hlUGOodnsaXpbyGOzdg==,type:bool]
report:
    discord:
        webhook_url: ENC[AES256_GCM,data:45A4aYhA3W9QmnqH75QJAi03i6/gZK4kd3Plo0FRDBusAVhlhLTDdvRjpAfmBEgbdFPLTKR7K8oGf5lGc64DJBNG0cH9LXXVpj4eIIOHJyOavdA+UhghL4gHzu90U4QXi0NIXJjCEWO5sHoXPMDYCaebTZyL2Xz6hA==,iv:aFtuJYsLMXBM8DrK+Ubz2xxKJV3VbPyu1grlJk3UCQ0=,tag:ftL/7ydCYamYxnIX9Hog3A==,type:str]
        enabled: ENC[AES256_GCM,data:rFpY1g==,iv:aLuIJsru2z0QTVHLodIcURU2iFqk2VzN/vwbt3Z0kJM=,tag:WkutNyMACoHrkUOVatLVuw==,type:bool]
        embed: ENC[AES256_GCM,data:kVXw0A==,iv:XYH48J+9fc09pgeTtybYwMdqAjWl25L44PQcqUH1nBA=,tag:M61cNt792dpdlWo+r4mO1w==,type:bool]
        colored: ENC[AES256_GCM,data:u/U42g==,iv:mxP668aowskeCTOTssGTukyMz471qpUhixgOQ3dpCus=,tag:0uordDF1gDXuddiuHOhRUw==,type:bool]
        subject: ENC[AES256_GCM,data:qQ6Xor6mplhRY4pMdK0qnzko3awdie4=,iv:ytVY2xEei5c8vKf0ut9vSrRcr8j8ZhhSQ8DwebO/rNE=,tag:9gJKzKCPJ2Vaw/obu+Bt0g==,type:str]
sops:
    age:
        - recipient: age1est4jdeu803qv6jng7vrj9x92l3xs0mr6qwv6fpt0p7tdd26xd6s84k2pq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDRTM5dWVzV085M1U0VGZp
            Z3RmVWFtZjg4SVQ2RmZwNm5DWk5KUkZsYUZZCm1aMVozT0daQUIvNFBmODRCbGZJ
            OTZjSzdscitGcmVKUjZJNXBXVHNzbEUKLS0tIFZObHRIYzBLZVJiOGJkNEhkVkk5
            ZFZRZkY4WWxNUG9ZYjVtZC83MU9vRDQKv1GAXpkf8QYtNKhPsFbX8HOBqF2jE04t
            p0y9VwJ1Epq0pT5np6+v7vkuJtBIrbp98QJJiwAjzAbTXjyHu627xg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1xaxgua4xzu7p9545hwnzpal8rlpza95wjyz2d4at8jajsx38w4tsp87z5d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuV2xUK09LY0x4dkR2MHNJ
            Sk50aVZVL21YMWwvT1JhdE5OM24xMzBaVkdjCkV4QU96Lzd4WE9KNG41NFF1b0M3
            NVBFYXZIOFdlUFR0d0lvOEovWDZwUEUKLS0tIG92ZFNyTlhRczNWb1lJMFBpaUJY
            Q29LUlI4alRhZ2JtbU9ndTlnYmFmM00KzVb0QLzx92SI1ULUkg2nrKNh/oy+q8j7
            A/63y5chFBO5/16L3SfhSsYCkK1uH5AiSOAN7nlC/90z/9UsrEjPJA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1w785k56chrrsc29jgkjzyvxfj3lx5sx56cm5fg6ldvychdga9umspddsfg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2OFdzQlNlbVE3Q0NVL3I5
            OGhQN2t3cHZSSWRScWlXK1phUlBRRUJBdWhRClJOclY3TVRXV085UWp4dDFUdGxx
            RXhBaHVOMnRhNG91S3hqaHpFRTJ1M0UKLS0tICs5QUluSW9CSlFJVDNWTlE1ZFNF
            NHRVMW1YSTQ1Q1RjV2Fzem1IUmtmMDgKXRyHmCydKOcROd7AVQqItC879LIWcyWE
            5sBKwHSwYcBBtUxlubIuMZaXayZxsfhLxipYsgiVvWJ36Bveh+Xrcw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-11T12:58:01Z"
    mac: ENC[AES256_GCM,data:APUL/33rX4Zbx0q8UrDBUopEcyfMDyUTGp0OhMOVBQVxqDHyhiA3NEMQQLuL8jdQ99k4Z7XzRdoKtKC7MMHfbq1OcKCOqs4Bcq16CShByZehvZtYm6rt7hwz2fbOFT7RqELeB8UzRkHKowrMBvyyTNfaKbu4ZpsI0/TjmYESCIs=,iv:ycz3/wmV9/kMMYhnzEpYIrI8l8R4kfCFGAYZu4CAtb4=,tag:8SFOm1bFhLyZUhhaIKsB4g==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
